---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations
  template:
    metadata:
      labels:
        app: recommendations
    spec:
      containers:
        - name: recommendations
          image: ghcr.io/f5devcentral/spa-demo-app-recommendations:sha-eb52ccf
          ports:
            - containerPort: 8001
          env:
            - name: SEED_FILE
              value: coffeeProducts.json
---
apiVersion: v1
kind: Service
metadata:
  name: recommendations
spec:
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: recommendations

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: ghcr.io/f5devcentral/spa-demo-app-inventory:sha-eb52ccf
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: inventory
spec:
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    app: inventory
