repoServer:
  containerSecurityContext:
    seccompProfile:
      type: Unconfined
configs:
  cm:
    resource.customizations: |
      Service:
        health.lua: |
          hs = {}
          hs.status = "Healthy"
          return hs