apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: ${k8s_namespace}
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: ${gcp_service_account}@${project}.iam.gserviceaccount.com
  name: ${k8s_service_account}
  namespace: ${k8s_namespace}